### ISSUE TITLE
Build Character 

### ISSUE THREAD

**Issue by Luc-Olsthoorn** [alaingarcia/The-Last-Warrior#5]
The main player needs to be built. This includes:

- [x] Jumping  

- [x] Grappling

- [x]  Animations

- [x] Running on the y 

- [x] Running on the x

- [x] Fighting (sword motion)
