### ISSUE TITLE
Environment

### ISSUE THREAD

**Issue by Luc-Olsthoorn** [alaingarcia/The-Last-Warrior#6]
- [x] Platforms, such as on top of 

- [ ] Trees, and tree mechanics, such as breaking, and wind. 

- [ ] Background scene

- [ ] Ground floor, with scenery such as grass

- [x] Atmosphere, such as fog

- [ ]  Lighting
