### ISSUE TITLE
Boss

### ISSUE THREAD

**Issue by Luc-Olsthoorn** [alaingarcia/The-Last-Warrior#7]
- [x] Create Boss Character assets

- [x] Implement jumping and grappling (should be stolen from main character)

- [x] Implement main algorithm to chase down main character, with things such as jumping 

- [x] Implement attack 

- [x] Implement health
